In [1]:
#SECTION A:
1.#	Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.
lst1=[201,202,211,218,281]

In [2]:
lst1

[201, 202, 211, 218, 281]

In [5]:
lst1.append("MANGO")

In [6]:
lst1

[201, 202, 211, 218, 281, 'MANGO', 'MANGO']

In [7]:
lst1.extend([12,"ala",1])

In [8]:
lst1

[201, 202, 211, 218, 281, 'MANGO', 'MANGO', 12, 'ala', 1]

In [9]:
lst1.remove("MANGO")

In [10]:
lst1

[201, 202, 211, 218, 281, 'MANGO', 12, 'ala', 1]

In [13]:
lst1.pop(4)

281

In [17]:
lst1

[201, 202, 211, 218, 'MANGO', 12, 'ala', 1]

In [14]:
lst1.count(1)

1

In [16]:
lst1.count(218)

1

In [18]:
lst1.count(281)

0

In [22]:
lst1.remove("MANGO")

In [23]:
lst1.remove("ala")

In [24]:
lst1

[201, 202, 211, 218, 12, 1]

In [25]:
lst1.sort()

In [26]:
lst1

[1, 12, 201, 202, 211, 218]

In [27]:
lst1.reverse()

In [28]:
lst1

[218, 211, 202, 201, 12, 1]

In [29]:
lst1.clear()

In [30]:
lst1

[]

In [34]:
2.#2.	Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.
tup1=(1,2,3,4,5,'project',[2,3,4])

In [35]:
tup1

(1, 2, 3, 4, 5, 'project', [2, 3, 4])

In [36]:
tup1[4]="AIML"

TypeError: 'tuple' object does not support item assignment

###### As we can see here we are getting an error because we cannot change an element in tuple but we can change the list in the tuple

In [37]:
3.#3.	Create a set of integers with some duplicate values. Print the set and explain the output
set1={1,False,11.2,11.2,"python",8+1j}

In [38]:
set1

{(8+1j), 1, 11.2, False, 'python'}

###### The set will not take the dupilcate values in the output

In [44]:
4.#4.	Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.
dict={
    "name":"EXCELR",
    "age":20,
    "city":"HYDERABAD"
}

In [45]:
dict

{'name': 'EXCELR', 'age': 20, 'city': 'HYDERABAD'}

In [46]:
dict["age"]=21

In [47]:
dict["email"]="excelr@gmail.com"

In [48]:
dict

{'name': 'EXCELR', 'age': 21, 'city': 'HYDERABAD', 'email': 'excelr@gmail.com'}

In [49]:
5.#Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.
age=int(input())
if(age>=18):
    print("eligible for vote.")
else:
    print("not eligible for vote")

 15


not eligible for vote


In [60]:
6.#6.	Given a 'marks' variable, print the grade:
#- 90 and above: 'A'
#- 75–89: 'B'
#- 50–74: 'C'
#- Below 50: 'Fail'
marks=int(input())
if marks>=90:
    print("A")
elif 75<=marks<=89:
    print("B")
elif 50<=marks<=74:
    print("C")
else:
    print("Fail")
    
    
    
    


 95


A


In [63]:
7.#7.	Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.
num=int(input())
if(num>0):
    if num%2==0:
        print("positive or even")
    else:
        print("positive but odd")
elif num==0:
    print("Zero")
else:
    print("negative")

 4


positive or even


In [69]:
#SECTION B:
#8.Create:
#- A scalar using np.array(5)
#- A 1D array with values 1 to 5
#- A 2D array (2x3) with values from 10 to 60 in steps of 10


In [70]:
import numpy as np
scalar=np.array(5)


In [71]:
scalar

array(5)

In [72]:
arr1=[1,2,3,4,5]
arr1

[1, 2, 3, 4, 5]

In [82]:
arr2=np.array([[10,20,30],[40,50,60]])

In [83]:
arr2

array([[10, 20, 30],
       [40, 50, 60]])

In [85]:
#9.	Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().
arr3=np.random.randint(0,100,size=(4,4))

In [86]:
arr3

array([[99, 85, 43, 68],
       [66, 91, 42, 61],
       [ 0, 40,  7,  3],
       [15, 21, 11, 56]], dtype=int32)

In [87]:
#10.Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.
import pandas as pd
arr4=np.random.randint(1,12,size=(3,3))
arr4

array([[11,  7,  9],
       [ 4,  5,  2],
       [ 3,  1,  1]], dtype=int32)

In [88]:
dataframe=pd.DataFrame(arr4)
dataframe

0  1  2
0  11  7  9
1   4  5  2
2   3  1  1

In [89]:
dataframe.columns=["A","B","C"]

In [90]:
dataframe

A  B  C
0  11  7  9
1   4  5  2
2   3  1  1

In [91]:
#SECTION C
#11.	Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
#- Use .info(), .describe()
#- Select 'Name' and 'City' columns
#- Drop 'City' column
#- Fill any missing values in 'Salary' column with the mean
#- Remove any duplicate rows


In [99]:
arr5= {
    "Name": ["Asha", "Ravi", "Sita", "Kiran", "Meena",
             "Arjun", "Divya", "Rahul", "Pooja", "Vikram"],
    "Age": [23, 25, 22, 24, 26, 27, 21, 28, 23, 29],
    "City": ["Hyderabad", "Delhi", "Mumbai", "Chennai", "Pune",
             "Kolkata", "Bangalore", "Delhi", "Mumbai", "Chennai"],
    "Salary": [30000, 40000, np.nan, 35000, 45000,
               50000, 38000, np.nan, 42000, 47000]
}



arr5

{'Name': ['Asha',
  'Ravi',
  'Sita',
  'Kiran',
  'Meena',
  'Arjun',
  'Divya',
  'Rahul',
  'Pooja',
  'Vikram'],
 'Age': [23, 25, 22, 24, 26, 27, 21, 28, 23, 29],
 'City': ['Hyderabad',
  'Delhi',
  'Mumbai',
  'Chennai',
  'Pune',
  'Kolkata',
  'Bangalore',
  'Delhi',
  'Mumbai',
  'Chennai'],
 'Salary': [30000, 40000, nan, 35000, 45000, 50000, 38000, nan, 42000, 47000]}

In [100]:
df1=pd.DataFrame(arr5)
df1

Name  Age       City   Salary
0    Asha   23  Hyderabad  30000.0
1    Ravi   25      Delhi  40000.0
2    Sita   22     Mumbai      NaN
3   Kiran   24    Chennai  35000.0
4   Meena   26       Pune  45000.0
5   Arjun   27    Kolkata  50000.0
6   Divya   21  Bangalore  38000.0
7   Rahul   28      Delhi      NaN
8   Pooja   23     Mumbai  42000.0
9  Vikram   29    Chennai  47000.0

In [101]:
df1.columns=["Name","Age","City","Salary"]

In [102]:
df1

Name  Age       City   Salary
0    Asha   23  Hyderabad  30000.0
1    Ravi   25      Delhi  40000.0
2    Sita   22     Mumbai      NaN
3   Kiran   24    Chennai  35000.0
4   Meena   26       Pune  45000.0
5   Arjun   27    Kolkata  50000.0
6   Divya   21  Bangalore  38000.0
7   Rahul   28      Delhi      NaN
8   Pooja   23     Mumbai  42000.0
9  Vikram   29    Chennai  47000.0

In [103]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes


In [104]:
df1.describe()

Age        Salary
count  10.00000      8.000000
mean   24.80000  40875.000000
std     2.65832   6556.076789
min    21.00000  30000.000000
25%    23.00000  37250.000000
50%    24.50000  41000.000000
75%    26.75000  45500.000000
max    29.00000  50000.000000

In [105]:
df1.describe(include="object")

Name   City
count     10     10
unique    10      7
top     Asha  Delhi
freq       1      2

In [107]:
df1[["Name","City"]]

Name       City
0    Asha  Hyderabad
1    Ravi      Delhi
2    Sita     Mumbai
3   Kiran    Chennai
4   Meena       Pune
5   Arjun    Kolkata
6   Divya  Bangalore
7   Rahul      Delhi
8   Pooja     Mumbai
9  Vikram    Chennai

In [118]:
#df1=df1.drop("City",axis=1)

In [117]:

df1


Name  Age   Salary
0    Asha   23  30000.0
1    Ravi   25  40000.0
2    Sita   22      NaN
3   Kiran   24  35000.0
4   Meena   26  45000.0
5   Arjun   27  50000.0
6   Divya   21  38000.0
7   Rahul   28      NaN
8   Pooja   23  42000.0
9  Vikram   29  47000.0

In [121]:
df1["Salary"]=df1["Salary"].fillna(df1["Salary"].mean())

In [122]:
df1

Name  Age   Salary
0    Asha   23  30000.0
1    Ravi   25  40000.0
2    Sita   22  40875.0
3   Kiran   24  35000.0
4   Meena   26  45000.0
5   Arjun   27  50000.0
6   Divya   21  38000.0
7   Rahul   28  40875.0
8   Pooja   23  42000.0
9  Vikram   29  47000.0

In [123]:
df1=df1.drop_duplicates()

In [124]:
df1

Name  Age   Salary
0    Asha   23  30000.0
1    Ravi   25  40000.0
2    Sita   22  40875.0
3   Kiran   24  35000.0
4   Meena   26  45000.0
5   Arjun   27  50000.0
6   Divya   21  38000.0
7   Rahul   28  40875.0
8   Pooja   23  42000.0
9  Vikram   29  47000.0